export default {
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOGOUT: 'LOGOUT',

  CREATE_ACCOUNT_PENDING: 'CREATE_ACCOUNT_PENDING',
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
  CREATE_ACCOUNT_ERROR: 'CREATE_ACCOUNT_ERROR',

  FETCH_RECIPES_PENDING: 'FETCH_RECIPES_PENDING',
  FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
  FETCH_RECIPES_ERROR: 'FETCH_RECIPES_ERROR',

  FETCH_RECIPE_PENDING: 'FETCH_RECIPE_PENDING',
  FETCH_RECIPE_SUCCESS: 'FETCH_RECIPE_SUCCESS',
  FETCH_RECIPE_ERROR: 'FETCH_RECIPE_ERROR',

  ADD_RECIPE_PENDING: 'ADD_RECIPE_PENDING',
  ADD_RECIPE_SUCCESS: 'ADD_RECIPE_SUCCESS',
  ADD_RECIPE_ERROR: 'ADD_RECIPE_ERROR'


};
